# Copyright 2021 The s6 Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

def adopt(arg0: object) -> None: ...
def adopt_existing_types() -> None: ...
def adopt_new_types() -> None: ...
def adoptable(arg0: object) -> bool: ...
def class_is_valid(arg0: object) -> bool: ...
def classid(arg0: object) -> int: ...
def get_class_attributes(arg0: object) -> dict: ...
def get_type_attributes(arg0: object) -> dict: ...
def stop_adopting_new_types() -> None: ...
